ifneq (,$(filter bm%160_spi,$(USEMODULE)))
  FEATURES_REQUIRED += periph_spi
  FEATURES_REQUIRED += periph_gpio
endif

ifneq (,$(filter bm%160_i2c,$(USEMODULE)))
  FEATURES_REQUIRED += periph_i2c
endif
